//
//  ShelfTrackApp.swift
//  rushthru
//
//  Created by Generated by ChatGPT.
//

import SwiftUI

@main
struct ShelfTrackApp: App {
    @StateObject private var environment = AppEnvironment()

    var body: some Scene {
        WindowGroup {
            RootView()
                .environmentObject(environment)
        }
    }
}
